CeladonCity_Condominiums_Roof_Text_IKnowEverything:: @ 81964C4
    .string "I KNOW EVERYTHING!$"

Text_IcyWindTeach::
    .string "The breeze feels nice up here.\n"
    .string "It's cold and refreshing.\p"
    .string "Time is flying past.\n"
    .string "You have to slow down.\p"
    .string "Like the move ICY WIND.\n"
    .string "It always slows your pace.\p"
    .string "What do you say? Shall I teach\n"
    .string "it to your POKéMON.$"

Text_IcyWindDeclined::
    .string "Come see me again if you change\n"
    .string "your mind.$"

Text_IcyWindWhichMon::
    .string "Which POKéMON wishes to learn\n"
    .string "ICY WIND?$"

Text_IcyWindTaught::
    .string "This gust of cold wind…\n"
    .string "It's like the rain that falls\l"
    .string "when summer ends.$"
