SevenIsland_Text_IslandSign:: @ 8183046
    .string "SEVEN ISLAND\n"
    .string "Quest Island of Infinity$"

SevenIsland_Text_IslandsMadeInSevenDays:: @ 818306C
    .string "These islands are called the SEVII\n"
    .string "ISLANDS because there are seven.\p"
    .string "…Or at least that's what the young\n"
    .string "people believe.\p"
    .string "The truth is, these islands are so\n"
    .string "named because they are said to\l"
    .string "have been made in seven days.$"

SevenIsland_Text_IslandVirtuallyUntouched:: @ 8183143
    .string "This island has been left virtually\n"
    .string "untouched in its natural state.\p"
    .string "It could be a little difficult to\n"
    .string "hike around because of that.$"

