CinnabarIsland_PokemonLab_Lounge_Text_WouldYouLikeToChangeNature::
    .string "Tch! I've come up with an amazing\n"
    .string "new technology.\p"
    .string "I can change the NATURE of your\n"
    .string "POKéMON.\p"
    .string "Would you like me to do that?$"

CinnabarIsland_PokemonLab_Lounge_Text_WhichMonShouldChangeNature::
    .string "Which POKéMON's nature\n"
    .string "should I change?$"

CinnabarIsland_PokemonLab_Lounge_Text_IncreaseWhichStat::
    .string "What do you want your\n"
    .string "POKéMON to be strong in?$"

CinnabarIsland_PokemonLab_Lounge_Text_DecreaseWhichStat::
    .string "What do you want your\n"
    .string "POKéMON to be weak in?$"

CinnabarIsland_PokemonLab_Lounge_Text_CancelNatureChange::
    .string "Let me know if you change your\n"
    .string "mind.$"

CinnabarIsland_PokemonLab_Lounge_Text_ConfirmNatureChange::
    .string "Are you sure?$"

CinnabarIsland_PokemonLab_Lounge_Text_NatureChangeSuccessful::
    .string "All done!\n"
    .string "Your POKéMON's nature has changed.$"

CinnabarIsland_PokemonLab_Lounge_Text_CantChangeNatureEgg::
    .string "I can't change the nature\n"
    .string "of an egg.$"
