CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers:: @ 8195BBA
    .string "POKéMON stat enhancers can be\n"
    .string "bought only here.\p"
    .string "HP UP increases the base HP of a\n"
    .string "POKéMON.\p"
    .string "CALCIUM raises the base SP. ATK\n"
    .string "stat of one POKéMON.\p"
    .string "ZINC boosts the base SP. DEF stat\n"
    .string "of one POKéMON.\p"
    .string "CARBOS enhances the base SPEED\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers:: @ 8195CA0
    .string "I'm here for POKéMON stat\n"
    .string "enhancers.\p"
    .string "PROTEIN increases the base ATTACK\n"
    .string "power.\p"
    .string "IRON increases the base DEFENSE\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore:: @ 8195D14
    .string "5F: DRUGSTORE$"

Text_ThunderPunchTeach::
    .string "HYAH!\n"
    .string "…\p"
    .string "Observe the real power of\n"
    .string "THUNDERPUNCH.\p"
    .string "Lightning flashes, and disappears.\n"
    .string "None can stop it.\p"
    .string "Let me teach this move\n"
    .string "to your POKéMON.$"

Text_ThunderPunchDeclined::
    .string "HYAH!\n"
    .string "I shall teach this at any time.$"

Text_ThunderPunchWhichMon::
    .string "Which POKéMON should learn\n"
    .string "THUNDERPUNCH?$"

Text_ThunderPunchTaught::
    .string "HYAH!\n"
    .string "When lightning strikes, it casts\l"
    .string "a shadow…$"
