CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent:: @ 8195A68
    .string "I'm getting a present for my\n"
    .string "girlfriend.\p"
    .string "I guess a POKé DOLL will be it.\n"
    .string "It's the popular thing.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll:: @ 8195AC9
    .string "I heard something useful.\p"
    .string "If a wild POKéMON appears, you can\n"
    .string "distract it with a POKé DOLL.\p"
    .string "You can run away while the wild\n"
    .string "POKéMON is distracted.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign:: @ 8195B5B
    .string "Express yourself with gifts!\n"
    .string "4F: WISE MAN GIFTS\p"
    .string "Evolution Special!\n"
    .string "Element STONES on sale now!$"

Text_IcePunchTeach::
    .string "HYAH!\n"
    .string "This packs a serious punch.\p"
    .string "Behold the power of\n"
    .string "ICE PUNCH.\p"
    .string "It bites like the arctic wind!\n"
    .string "Like a sub-zero slammer.\p"
    .string "Say, I teach this move to\n"
    .string "to your POKéMON.$"

Text_IcePunchDeclined::
    .string "HYAH!\n"
    .string "You will be back, I'm certain!$"

Text_IcePunchWhichMon::
    .string "Which POKéMON should learn\n"
    .string "ICE PUNCH?$"

Text_IcePunchTaught::
    .string "HYAH!\n"
    .string "Frozen in time!$"
